sudo: required
language: node_js
node_js:
  - '9'
  - '8'
  - '6'

addons:
  chrome: stable

before_script:
  - node --version
  - npm --version

script:
  npm run ci

after_success:
  - cat ./coverage/coverage.json | node_modules/codecov.io/bin/codecov.io.js
  - rm -rf ./coverage

matrix:
  fast_finish: true
