sudo: required
language: node_js
node_js:
  - '10'
  - '8'
  - '6'

addons:
  chrome: stable

before_script:
  - node --version
  - npm --version

script:
  npm run ci

after_success:
  - ./node_modules/.bin/codecov
  - rm -rf ./coverage

matrix:
  fast_finish: true
